### Quick Look

In [11]:
import os
baudrillard = '/Users/finchmf/coding/TwitterRitual/core/behavior/text/webscraper/baudrillard/textData/simulacra-and-simulation.txt'
baudrillard_2 = '/Users/finchmf/coding/TwitterRitual/core/behavior/text/webscraper/baudrillard/textData/simulations.txt'
def load_data(path: str) -> str:

    text_file = os.path.join(path)
    with open(text_file, "r") as f:
        data = f.read()

    return data

_data = load_data(baudrillard)
_data_2 = load_data(baudrillard_2)
main_data = _data + _data_2

In [12]:
import numpy as np

view_line_range = (100, 150)

print('Dataset Stats')
print('Roughly the number of unique words: {}'.format(len({word: None for word in main_data.split()})))

lines = main_data.split('\n')
print('Number of lines: {}'.format(len(lines)))
word_count_line = [len(line.split()) for line in lines]
print('Average number of words in each line: {}'.format(np.average(word_count_line)))

print()
print('The lines {} to {}:'.format(*view_line_range))
print('\n'.join(main_data.split('\n')[view_line_range[0]:view_line_range[1]]))

Dataset Stats
Roughly the number of unique words: 14440
Number of lines: 11204
Average number of words in each line: 7.909139593002499

The lines 100 to 150:
whose operation is nuclear and genetic, no longer at all specular or discursive. It is all of 
metaphysics that is lost. No more mirror of being and appearances, of the real and its 
concept. No more imaginary coextensivity: it is genetic miniaturization that is the 
dimension of simulation. The real is produced from miniaturized cells, matrices, and 
memory banks, models of control - and it can be reproduced an indefinite number of 
times from these. It no longer needs to be rational, because it no longer measures itself 
against either an ideal or negative instance. It is no longer anything but operational. In 
fact, it is no longer really the real, because no imaginary envelops it anymore. It is a 
hyperreal, produced from a radiating synthesis of combinatory models in a hyperspace 
without atmosphere. 

By crossing into a spac

### More Developed Dive

In [19]:
from utils import data

baudrillard = '/Users/finchmf/coding/TwitterRitual/core/behavior/text/webscraper/baudrillard/textData/simulacra-and-simulation.txt'
baudrillard_2 = '/Users/finchmf/coding/TwitterRitual/core/behavior/text/webscraper/baudrillard/textData/simulations.txt'

text = data.convertManyToOne([baudrillard, baudrillard_2])

tmp_path = '/Users/finchmf/coding/TwitterRitual/core/behavior/text/webscraper/baudrillard/textData/tmp'
tmp_file = 'tmp_combined.txt'

if not os.path.exists(tmp_path):
    os.mkdir(tmp_path)

with open(f'{tmp_path}/{tmp_file}', 'w') as f:

    f.write(text)
    f.close()

data.preprocess_and_save(
    text_path=f'{tmp_path}/{tmp_file}',
    text_title='baudrillard_combined'
)
int_text, w2i, i2w, token_dict = data.load_preprocess('baudrillard_combined')

In [20]:
import torch

train_on_gpu = torch.cuda.is_available()
if not train_on_gpu:
    print('CPU')

CPU


In [21]:
import numpy as np
from torch.utils.data import TensorDataset, DataLoader

def batch_data(words: list, sequence_length: int, batch_size: int) -> DataLoader:

    words = np.array(words)
    total_batch_size = batch_size * sequence_length
    n_batches = len(words) // batch_size

    words = words[:n_batches * total_batch_size]

    feature, target = [], []

    target_words_length = words[:-sequence_length]
    for idx in range(0, len(target_words_length)):

        feature.append(words[idx: idx + sequence_length])
        target.append(words[idx + sequence_length])

    batch_nums = len(words) // batch_size
    feature = feature[:batch_nums * batch_size]
    target = target[:batch_nums * batch_size]

    feature_tensors = torch.from_numpy(np.asarray(feature))
    target_tensors = torch.from_numpy(np.asarray(target))

    data_set = TensorDataset(feature_tensors, target_tensors)

    data_loader = DataLoader(data_set, batch_size=batch_size, shuffle=True)

    return data_loader

In [22]:
# test dataloader

test_text = range(50)
t_loader = batch_data(test_text, sequence_length=5, batch_size=10)

data_iter = iter(t_loader)
sample_x, sample_y = data_iter.next()

print(sample_x.shape)
print(sample_x)
print()
print(sample_y.shape)
print(sample_y)

torch.Size([10, 5])
tensor([[20, 21, 22, 23, 24],
        [39, 40, 41, 42, 43],
        [ 2,  3,  4,  5,  6],
        [26, 27, 28, 29, 30],
        [ 6,  7,  8,  9, 10],
        [28, 29, 30, 31, 32],
        [17, 18, 19, 20, 21],
        [40, 41, 42, 43, 44],
        [11, 12, 13, 14, 15],
        [33, 34, 35, 36, 37]])

torch.Size([10])
tensor([25, 44,  7, 31, 11, 33, 22, 45, 16, 38])


In [23]:
n_loader = batch_data(int_text, sequence_length=7, batch_size=32)

In [27]:
data_iter = iter(n_loader)
x,y = data_iter.next()

print(x)
print(y)

tensor([[   75, 10252,     1,     0,   154,    18,    11],
        [   17,   205,     1,     3,    40,   448,   706],
        [    0,   194,   825,    25,     8,     0,  1246],
        [    4,  4326,     8,     2,     6,     9,   264],
        [ 1005,   582,    14,  1991,     0,   110,     1],
        [ 1259, 11146, 11147,   199,   119,     3,    39],
        [  841,     1,     9,  1156,  2425,  1104,     0],
        [   36,    48,  2153,    92, 13302,     5,     0],
        [  225,    10,    32,  2107,   129,  4181,    22],
        [ 5698,     1,     0,  1489,     7,     2,    28],
        [    0,  3289,  3290,    26,     0,   691,   219],
        [    2,     0,  5353, 10005,     1,     0,   154],
        [  300,   669,    95,     4,     1,     0,   902],
        [  258,     5,     0,  8016,     4,     6,     3],
        [   19,     0,  6853,     2,    57,    58,     0],
        [    0,  1105,     6,    14,   278,    85,   136],
        [  143,  4720,     8,  1222,  2286,   336,   241